### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-2-evaluacion-intermedia-TaniaGamGonz#1]
Really cool job @TaniaGamGonz !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [x] If a variable is only used within one function, you can declare it locally. (this: <https://github.com/Adalab/modulo-2-evaluacion-intermedia-TaniaGamGonz/blob/263013435e95db17ca7ad174adbf8b4e91ae2e72/js/main.js#L4-L5>)
- [x] Use return to transfer values between functions (from called function to caller code). I.E: playerChoice
- [x] Watch out for constant names used to save DOM references... Do we want to use the DOM reference or that DOM element content (innerHTML/value)? (this names: <https://github.com/Adalab/modulo-2-evaluacion-intermedia-TaniaGamGonz/blob/263013435e95db17ca7ad174adbf8b4e91ae2e72/js/main.js#L11-L13>)

### JavaScript: advanced

- [x] Check if the `<select>` has the default option (with no value).

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Show an image with the user and computer selection
- Make the input work when selecting the option.
- Add a reset button that cleans the select, the counter and writes the initial feedback
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by igarridomorillas** [comment]
Perfect!
